spring:
  data:
    mongodb:
      database: ${DATABASE_NAME}
      host: ${DATABASE_HOSTNAME}
      port: ${DATABASE_PORT}
secret-key: ${SECRET_KEY}
token-expiration-ms: ${TOKEN_EXPIRATION_MS}